-- CREATE TABLE characters (
--     id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
--     name TEXT NOT NULL
-- );
-- CREATE TABLE connections (
--     char_id_1 INTEGER NOT NULL,
--     char_id_2 INTEGER NOT NULL,
--     FOREIGN KEY(char_id_1) REFERENCES characters(id),
--     FOREIGN KEY(char_id_2) REFERENCES characters(id)
-- );
-- CREATE TABLE users (
--     id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
--     username TEXT NOT NULL,
--     hash TEXT NOT NULL,
--     is_admin BIT NOT NULL DEFAULT 0
-- );